### PR TITLE
Add .gitignore

### PR DESCRIPTION
**Pull request by xexyl**
Added .DS_Store, prog and alt.prog.

This is also an experiment to see if this can be merged into the temp-test-ioccc repo but in a way that won't hurt if it can't be.

### CODE REVIEW

**Comment by xexyl** [comment]
BTW: mirror-request.html is out of date also but in a way I'm not sure how to fix or what to change it to.

**Comment by xexyl** [comment]
What is this repeat clone request please ?

**Comment by lcn2** [comment]
> What is this repeat clone request please ?

Your pole request was made against the primary website tree and not this repo. However, we let it go because it was useful and it need to be applied to this repo so we change this repo in an identical way. 

In general, when you go to pull request, you need to make a pull request against this repo only.

**Comment by xexyl** [comment]
> > What is this repeat clone request please ?
> 
> Your pull request was made against the primary website tree and not this repo. However, we let it go because it was useful and it need to be applied to this repo so we change this repo in an identical way.
> 
> In general, when you go to pull request, you need to make a pull request against this repo only. Don't update the ioccc-src/winner repo. Update only this repo.

As I noted I can't do that ... working on gathering as much information as I can to show the problem. But thank you for merging this. I will now see if I can figure out a way to fork the temp repo. I'm not hopeful but maybe the information I will give can help identify the problem. Until it's resolved I don't see how I can help much at least as far as making changes. :(

**Pull request merged**
