### PR TITLE
Solved bug in 2006/Toledo2 for x86_64 Mac, also clarified from where appears HALT.COM and IMPORT.COM files.

### PR DESCRIPTION
**Pull request by nanochess**
The bug in x86_64 Mac happened because a pointer was copied into an integer, and then back to pointer. It was solved by copying the pointer in an unused variable 'e' with type FILE * remaining from the initial memory binary loading. Also, I've clarified that the HALT.COM and IMPORT.COM files are created by the provided C.BIOS file.

### CODE REVIEW

**Comment by xexyl** [comment]
Wrong repo though. I thought I fixed this issue but maybe it's something else. I can barely see right now. The other information is great. Anyway I'm sure Landon can tell you about the other repo as I can't right now.

**Comment by xexyl** [comment]
If the bug you refer to is a crash this was indeed fixed by me some time back. Just checked. Was it some other problem?

**Comment by nanochess** [comment]
Yes, it copied a FILE pointer through an integer and mangled it, so it crashed when compiling on x86_64 Mac.
The corrected part is: (fseek(e=5[k]-1?u:v,((3[k]|4[k]<<8)<<7|2[k])<<7,Q=0),e
Where y (2 instances) was replaced with e.

I also made some changes to the README.md to point to the required files for running CP/M, and clarified that you don't need to download HALT.COM or IMPORT.COM as these are created by the provided C.BIOS.

**Comment by xexyl** [comment]
> Yes, it copied a FILE pointer through an integer and mangled it, so it crashed when compiling on x86_64 Mac. The corrected part is: (fseek(e=5[k]-1?u:v,((3[k]|4[k]<<8)<<7|2[k])<<7,Q=0),e Where y (2 instances) was replaced with e.
> 
> I also made some changes to the README.md to point to the required files for running CP/M, and clarified that you don't need to download HALT.COM or IMPORT.COM as these are created by the provided C.BIOS.

Already fixed in the temp repo which will be folded into the winner repo later on - by changing to `FILE *`. You might want to update the README.md there with what you did here. But the bug is already fixed.

**Comment by xexyl** [comment]
> > Yes, it copied a FILE pointer through an integer and mangled it, so it crashed when compiling on x86_64 Mac. The corrected part is: (fseek(e=5[k]-1?u:v,((3[k]|4[k]<<8)<<7|2[k])<<7,Q=0),e Where y (2 instances) was replaced with e.
> > I also made some changes to the README.md to point to the required files for running CP/M, and clarified that you don't need to download HALT.COM or IMPORT.COM as these are created by the provided C.BIOS.
> 
> Already fixed in the temp repo which will be folded into the winner repo later on - by changing to `FILE *`. You might want to update the README.md there with what you did here. But the bug is already fixed.

Of course maybe it's something else you're thinking of. Anyway it's the wrong repo for this. I'd offer to help more but I can barely see right now.

**Comment by nanochess** [comment]
I'm pretty sure I cloned the temp-test-ioccc repo, I'm not sure why it tried to go into main. Sorry for that! I'll check later.

**Comment by xexyl** [comment]
> I'm pretty sure I cloned the temp-test-ioccc repo, I'm not sure why it tried to go into main. Sorry for that! I'll check later.

Had the same problem before. No idea how I fixed it. That was early last year and a lot has gone on. Happy new year!

**Comment by nanochess** [comment]
Happy new year!

**Comment by lcn2** [comment]
Thank you for applying your recommendations to the [temp-test-ioccc IOCCC repo](https://github.com/ioccc-src/temp-test-ioccc), where we hope that a cleaner web site will come along with a simplified IOCCC process to select and announce and publish IOCCC winners.

You, @nanochess, should know that your frustrations with how slow the IOCCC went from announcing the winners to finally posting the winning source has a significant impact on some of the IOCCC judges. 

Our new process where the next IOCCC winners will be announced, the winning IOCCC write ups will be made available, and the winning IOCCC source will be published: all at the same time via a single `git push` command. 

The internal links and the updates of the top level IOCCC web site will be accomplished by a single command `make install` (followed by the `git push` of course).  

Post publishing corrections,  improvements and other changes can be made via a **GitHub pull request** by persons such as yourself is another thing we wish to accomplish. 

Management of winner information (e.g., name, email, country/location, web site, secondary web site, GitHub handle, Mastodon handle, etc.) can be made via a  **GitHub pull request** that modifies a straightforward JSON file. (In your case that would be to modify [author/Oscar_Toledo.json](https://github.com/ioccc-src/temp-test-ioccc/blob/master/author/Oscar_Toledo.json). 

Along the way we are taking@ the time to enlist volunteers (other people are welcome to participate) to cleanup and in some cases repair very old IOCCC winners that cannot even compile on modern systems.  In addition we are taking to time to cleanup winner write ups, fix typos, and make someone more consistent across the years.

There is also a complete overhaul on how contestants will package their submission into a single compressed tarball via the **mkiocccentry** command via the [mkiocccentry repo](https://github.com/ioccc-src/mkiocccentry). 

And there is the submission server where registered contest users will be able to upload their **mkiocccentry** prepared compressed tarball and receive feedback that the IOCC judges received it and found the tarball to be in "good order" or that something went wrong along with a short statement of the problem. One will be able up update a given entry as needed while the IOCCC contest is open. The submission server has been prototyped, but needs further development. 

And registration for an IOCCC will be a process of joining a IOCCC contest specific mailing list and receiving a UUID reply: a contest ID that will be used via the above mentioned submit server. The vendor for the mailing list has been preliminary selected, and needs to be tested. 

We plan to **BETA TEST** all the above by holding a short **mock IOCCC**, where the entire IOCCC process is being tested end to end, corrections being applied and the **mock IOCCC** restated if necessary. The **mock IOCCC** won't judge C code (we will ask for simple "hello, world" code).  **Mock winners** will be those who helped identify and fix bugs, or otherwise helped improve the process. 

We just had our 4000th commit to the [temp-test-ioccc IOCCC repo](https://github.com/ioccc-src/temp-test-ioccc) since the fork from the [official IOCCC website](https://github.com/ioccc-src/winner).  We plan to perform the **great merge** when those 4000+ mods will be applied to the [official IOCCC website](https://github.com/ioccc-src/winner). Until that time,  changes such as what you offers will be applied to the [temp-test-ioccc IOCCC repo](https://github.com/ioccc-src/temp-test-ioccc) only. 

We are **VERY AWARE THE LAST IOCCC was in 2020**. We regret the inconvenience and delay in starting of IOCCC28.  But we believe that the new process will be cleaner, faster and better.  No longer will, for example, the procrastination of a single IOCCC judge be able hold up the release of the wining code, delay the start of judging, or impact our ability to update the website. 

We ask your pardon for the delay in IOCCC28 and thank you and input, feedback and patience you may wish to share.

**Comment by xexyl** [comment]
As far as those that won't compile with modern systems I took care of that. With the exception of some that won't completely compile with clang or specific platforms (e.g. those that can't compile 32-bit code but the entries are 32 bit specific - and I fixed many of those actually) at least.

Of course there's the one by Westley that is supposed to fail to compile - different error messages depending on the compiler line in order to 'escape the dungeon' but that's not an error in the traditional sense.

I am aware of one entry that was supposed to do some animation when compiling but that depends on the compiler version unfortunately.

Some entries only work with some compilers even besides compilation issues particularly if it's parsing warnings in the compiler. Even so most of those have been fixed too.

Of course 1984/mullender is not supposed to run on modern systems but the alt code I added does and some entries allow it to run too. In one case the version of perl in macOS prevents it from running right.

But mostly this task is done. Still a number of entries with known bugs that could be fixed that I haven't done (yet? But right now I have more important things to do for the contest so if I do fix those it'll be in 'off time' after the next contest).

Lots to do still of course. It's nice to see you Oscar! I almost tried to contact you about the missing files (or was it something else? I don't even remember now: so many things I have gone through and other things going on in my life).

**Comment by nanochess** [comment]
Hey Landon! Of course, I remember waiting months for the contest public releases and the slow message bouncing for corrections, but I understood these were normal because of the judges' occupations. Anyway, I've fond memories of the IOCCC.

I'm glad to read that the process will be streamlined and much more comfortable for the judges and the contestants.

It is pretty nice to be the 4000th commit!

I'm tempted to give a look and try to help. And Cody thank you very much for your patience with my first commit.

**Comment by ilyakurdyukov** [comment]
The number of commits is NOT a sign of quality nor progress. It just reflects personal style of committing changes.

**Comment by lcn2** [comment]
> The number of commits is NOT a sign of quality nor progress. It just reflects personal style of committing changes.

Correct @ilyakurdyukov it is not a sign of quality nor a sign of progress.

Nevertheless it is fun to celebrate a number, and it was **fun** 😀 to let @nanochess know his was the pull request for which we passed that marker.

**Comment by ilyakurdyukov** [comment]
I want to note that I unsubscribed from `mkioccentry` updates because I was receiving too many notifications. There are too many messages and small commits.

**Comment by lcn2** [comment]
> I want to note that I unsubscribed from `mkioccentry` updates because I was receiving too many notifications. There are too many messages and small commits.

noted

**Comment by xexyl** [comment]
> > The number of commits is NOT a sign of quality nor progress. It just reflects personal style of committing changes.
> 
> Correct @ilyakurdyukov it is not a sign of quality nor a sign of progress.
> 
> Nevertheless it is fun to celebrate a number, and it was **fun** 😀 to let @nanochess know his was the pull request for which we passed that marker.

Not only is it fun the fact remains that the **QUALITY HAS INCREASED** and **WE HAVE MADE GREAT PROGRESS** whether or not the number of commits says so. But in actuality this is the case here: this (and the next parts) could not have been done in fewer commits. You should know, @ilyakurdyukov, that I have seen to it that all entries now compile (except maybe two or three that are very platform specific and in some cases I have added alt code) where many many older entries did not. You should also know that macOS does not have gcc: it's clang even the gcc binary. Clang doesn't to support `-traditional-cpp` but I made all entries that require this not require this. 

Most entries that no longer worked do now work. If that's not quality and progress I don't know what is. Many other changes have been done that increase the quality and show great progress.

**Comment by xexyl** [comment]
> I want to note that I unsubscribed from `mkioccentry` updates because I was receiving too many notifications. There are too many messages and small commits.

Smaller commits are easier to check and also are better for accounting purposes.

**Comment by xexyl** [comment]
> Hey Landon! Of course, I remember waiting months for the contest public releases and the slow message bouncing for corrections, but I understood these were normal because of the judges' occupations. Anyway, I've fond memories of the IOCCC.
> 
> I'm glad to read that the process will be streamlined and much more comfortable for the judges and the contestants.
> 
> It is pretty nice to be the 4000th commit!
> 
> I'm tempted to give a look and try to help. And Cody thank you very much for your patience with my first commit.

No problem on my behalf. If you want to help check the bugs.md file. Sorry for no link here. I need to leave.

**Comment by ilyakurdyukov** [comment]
> > I want to note that I unsubscribed from `mkioccentry` updates because I was receiving too many notifications. There are too many messages and small commits.
> 
> Smaller commits are easier to check and also are better for accounting purposes.

No, because it's hard to dig through the history of thousands of commits.

This is also bad because people who could observe your changes by subscribing to updates will quickly unsubscribe from the updates, as I did, or stop reading them. Because few people have that much time to check dozens of changes every day.

**Comment by xexyl** [comment]
> > > I want to note that I unsubscribed from `mkioccentry` updates because I was receiving too many notifications. There are too many messages and small commits.
> 
> > 
> 
> > Smaller commits are easier to check and also are better for accounting purposes.
> 
> 
> 
> No, because it's hard to dig through the history of thousands of commits.
> 
> 
> 
> This is also bad because people who could observe your changes by subscribing to updates will quickly unsubscribe from the updates, as I did, or stop reading them. Because few people have that much time to check dozens of changes every day.

Few people have the time that I put into it too. So that doesn't matter. Anyway Landon requested that I do this. Like it or not.

**Comment by ilyakurdyukov** [comment]
> Few people have the time that I put into it too. So that doesn't matter. Anyway Landon requested that I do this. Like it or not.

I don't like that this has become some kind of honorable mission for you, which you consider a reason for pride.

**Comment by xexyl** [comment]
> > Few people have the time that I put into it too. So that doesn't matter. Anyway Landon requested that I do this. Like it or not.
> 
> 
> 
> I don't like that this has become some kind of honorable mission for you, which you consider a reason for pride.

You do know what assumptions do, don't you? Because you're making assumptions. And most people don't like others coming out of the blue just to criticise their work and then go even further and criticise them for defending their work by telling the truth and then going and criticising them over an assumption.

Which is exactly what you're doing. 

But even if I am proud there are reasons to be proud. 

So if you don't like it you need to stop criticising people for their work that you played no part in. It's not even constructive criticism. It's just flat out criticism and it's rude. 

And that's not even considering that you criticised others too (for it's not just me). 

Good day.

**Comment by ilyakurdyukov** [comment]
> So if you don't like it you need to stop criticising people for their work that you played no part in. It's not even constructive criticism. It's just flat out criticism and it's rude.

I wanted to participate in this work, but you are doing everything to displace others and replace their code with yours. You're doing this on purpose, that's what's rude.

**Comment by lcn2** [comment]
Please stop this discussion.

**Comment by xexyl** [comment]
> Please stop this discussion.

Thank you. I almost didn't reply at all. I'm certainly bemused though.

**Pull request closed without merging**
