### PR TITLE
Make 1998/fanf more like the original

### PR DESCRIPTION
**Pull request by fanf2**
Hello, world! I'm happy to see the revamped IOCCC website. It's great that the winners are being maintained as both a showcase and an archive.

I had a look at my winner to see what needed fixing, and I've greatly reduced the changes that are necessary for modern systems. I've added some notes to `thanks-for-help` explaining the changes, and removed the caveat from the README since the code is now much closer to the original.

### CODE REVIEW

**Comment by xexyl** [comment]
Great!

If you have macOS or a recent enough version of bash and pandoc and other tools you should try:

```sh
make thanks quick_readme2index
```

.. but if you don't we can take care of it, Landon or me.

**Comment by xexyl** [comment]
As for the no arg to main you could add a `void` to it or it's possible that there is a way to disable the warning. Then you could remove that part from the files you edited (that link to the FAQ). If not then it's unfortunate but is what it is.

(I did not look at the patch btw so maybe I missed something - working on fixing issues due to changes in rule 17.)

Hope these comments are helpful!

BTW: what I really like is that you were able to get it to be the non-translated version! That's great! It was an unfortunate issue indeed.

**Comment by xexyl** [comment]
One more thing. If `main` only has one arg (looking at the diff it seems it could but. you say otherwise and given the C pre-processor abuse it's entirely possible I missed it) it is a problem because some versions of clang reject it outright.

But I guess you sorted that out already.

Best wishes and happy new year!

**Comment by xexyl** [comment]
Oh I noticed a few more things that might want to be fixed.

First though:

> Fun fact: T for Tony is once again the only letter not used in fanf.c

That is fun!

Second:

As for the ` -Wno-strict-prototypes`: if that is to prevent the one arg only to main: that will not fix the problem with `clang` so if it does only have one arg you should add the second arg back (I checked the clang source code and there's no way last I knew to disable the restriction). This is an unfortunate issue with clang. :(

Finally:

The line in the Makefile:

```makefile
-include ../../1337.mk
```

is actually incorrect. It needs to be:

```makefile
-include 1337.mk ../1337.mk ../../1337.mk
```

The reason for this is for the individual tarballs. Without it rules will break.

I think that's all I see. Don't mean to trample on your **GREAT** work: just helping out since you don't know about all the way things work now.

Great job!

**Comment by fanf2** [comment]
Many thanks for the quick review!

wrt the Makefile: oops, I somehow failed to undo that mistake, but after some coffee and a banana I have sorted it out.

wrt `make thanks quick_readme2index`, I need to install `mkiocccentry` et al., but I can do that after writing this comment.

wrt `main()` the code is now

        main ( x i ) ! (

which expands to

        main () { return (int)!(

which is why it now needs  `-Wno-strict-prototypes`.

The original code was

        main k i ) ! (

which expands to

        main (int c) { return (int)!(

The variable `c` isn't used. IIRC `main()` was defined like that because it's shorter, it avoids a `void`, and it avoids warnings about pre-standard K&R function definitions. To choose a fix I need to decide whether being short is more important than being ANSI. It's hard to decide but I think brevity wins: there are lots of other `-Wno-strict-prototypes` programs in this repository and pre-standard C was still relatively common in the late 1990s.

The other fix I considered was

        main ( void x i ) ! (

but, on balance, nah.

**Comment by xexyl** [comment]
> Many thanks for the quick review!
> 

I am happy to help out and i'm glad you appreciated it! Once it's merged the html files can be regenerated. I should check to see if that's in the FAQ. If it is not it was an oversight on my part.

> wrt the Makefile: oops, I somehow failed to undo that mistake, but after some coffee and a banana I have sorted it out.

As I have joked before:

```
Nobody is perfect. I am nobody. Therefore I am perfect and you're not! :-)
```

.. which is to say that mistakes do happen, as you and most other people know. I'm certainly far from perfect and I would not want to be perfect either!


> 
> wrt `make thanks quick_readme2index`, I need to install `mkiocccentry` et al., but I can do that after writing this comment.

That's true. But if you don't get it Landon or I can take care of it. In some systems it's problematic anyway as even if you install those tools you might not have a recent enough version of say pandoc. Iirc it might be that the action is only supported in macOS (not to say it wouldn't work otherwise of course).

> 
> wrt `main()` the code is now
> 
> ```
>     main ( x i ) ! (
> ```
> 
> which expands to
> 
> ```
>     main () { return (int)!(
> ```
> 
> which is why it now needs `-Wno-strict-prototypes`.
> 
> The original code was
> 
> ```
>     main k i ) ! (
> ```
> 
> which expands to
> 
> ```
>     main (int c) { return (int)!(
> ```
> 
> The variable `c` isn't used. IIRC `main()` was defined like that because it's shorter, it avoids a `void`, and it avoids warnings about pre-standard K&R function definitions. To choose a fix I need to decide whether being short is more important than being ANSI. It's hard to decide but I think brevity wins: there are lots of other `-Wno-strict-prototypes` programs in this repository and pre-standard C was still relatively common in the late 1990s.
> 

Well as long as it expands to zero or 2 args (or 3) it's fine for clang. I just wanted to be sure!

> The other fix I considered was
> 
> ```
>     main ( void x i ) ! (
> ```
> 
> but, on balance, nah.

That's fair. 

A lot going on in the repo which is great news! I'm glad you could get this much more like before. It was a strange fix or maybe workaround as for what I did. In some systems it worked and in others it did not. I could swear that later on a system that worked didn't work .. but a lot was done.

Best wishes!

**Comment by fanf2** [comment]
I'm afraid I've been defeated by the JSON tooling. I don't want to install `jsp` since it's python which is a massive pain in the arse, and I can't get the wrapper scripts to work with `JSONPath.sh`. (I wonder why it doesn't use `jq`.)

**Comment by xexyl** [comment]
> I'm afraid I've been defeated by the JSON tooling. I don't want to install `jsp` since it's python which is a massive pain in the arse, and I can't get the wrapper scripts to work with `JSONPath.sh`. (I wonder why it doesn't use `jq`.)

It can be taken care of .. no worries. Thanks for trying!

And as for the tools of choice. It's because I haven't written a certain tool yet that comes from the jparse repo. That however is post IOCCC28. Once that is done some of the workarounds can be removed.

**Review by lcn2 — APPROVED** [review]
Thanks @fanf2

**Comment by lcn2** [comment]
Thank you @fanf2 

As mentioned in [GH-issuecomment-2565947996](https://github.com/ioccc-src/winner/pull/36#issuecomment-2565947996) there will be a slight delay as we render the HTML changes and push it to GitHub and then GitHub updates the web site.

**Comment by lcn2** [comment]
The effect of this PR is reflected in commit 1f306dad844a8feefbafbaffae664a89f12a00c4 and should appear on the web site as soon as GitHub finishes the pages update.

**Pull request merged**
