### PR TITLE
Fixes to my two 2020 winning entries

### PR DESCRIPTION
**Pull request by xexyl**
Perhaps most importantly these commits have an important update to the cake recipe: use ONLY **pure vanilla extract**: not imitation vanilla! You can all thank my birthday (which is today) for this information as this is the second time using pure vanilla extract after at one point we had imitation (due to pure not being available at the time)! :)

But it also allows for the Snake scripts to work (due to the way the markdown files were changed from `*.markdown` to `*.text` and the fact the Makefile had those files as a dependency as well as the scripts running `make` after configuration the scripts failed).

I made some changes in the markdown too so that lists should be properly generated.

There were other changes.

### CODE REVIEW

**Comment by xexyl** [comment]
Btw if the html files did not get created right please let me know and what is missing and I'll fix them.

Will they be copied over to the IOCCC server? If not can they be?

**Comment by lcn2** [comment]
Thanks .. we will pull them into the site when we are able to perform the merge.  Please give us some time to do this.

**Comment by xexyl** [comment]
No worries. Seems I missed this reply too. Sorry about that.

**Comment by lcn2** [comment]
Pull request complete, thanks for your patience

**Comment by xexyl** [comment]
> Pull request complete, thanks for your patience

Thank you! Now I can actually update my website as well and note that one does not need to use the tarball I provided there. That'll probably not happen today either though.

Enjoy the rest of your weekend!

**Comment by xexyl** [comment]
...though ironically the last few days I have thought about updating some of the markdown files. Thus it's probable that in the future there will be another pull request for these (fixes as well I think - would have to look at what I have).

I also know that there's an issue with the remarks on weasel words entry as well. But these can be dealt with another time.

Enjoy the rest of your day my friend!

**Pull request merged**
